width = float(input("Enter width:"))
height = float(input("Enter height:"))
print("---------------------------")
print("1.",width//2,type(width//2))
print("2.",width/2.0,type(width/2.0))
print("3.",height/3,type(height/3))
print("4.",1+2*5,type(1+2*5))
